os: osx
language: generic

# only build on tag releases
if: tag IS present

jobs:
  include:
    - stage: Run Sylph on AWS Device Farms
      env: Run Sylph on AWS Device Farms
      before_install:

      # install correct version of java on osx to run sdkmanager
      - java -version
      - export HOMEBREW_NO_AUTO_UPDATE=1
      - brew cask uninstall java; brew tap caskroom/versions; brew cask install java8;
      - java -version

      # Install android tools
      - ANDROID_SDK_TOOLS=4333796 # android-28
      - ANDROID_PLATFORM_SDK=28
      - ANDROID_BUILD_TOOLS=28.0.3
      - export ANDROID_HOME=~/android-sdk
      - wget -q "https://dl.google.com/android/repository/sdk-tools-darwin-$ANDROID_SDK_TOOLS.zip" -O android-sdk-tools.zip
      - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
      - rm android-sdk-tools.zip
      - PATH=${PATH}:${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
      # Silence warning.
      - mkdir -p ~/.android
      - touch ~/.android/repositories.cfg
      # Accept licenses before installing components, no need to echo y for each component
      - yes | sdkmanager --licenses
      - sdkmanager --list | head -15
      # Platform and build tools
      - sdkmanager "tools" "platform-tools" "platforms;android-${ANDROID_PLATFORM_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
      - sdkmanager --list | head -15

      # fix timezone warning on osx
      - sudo ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime

      # setup osx environment for flutter
      - export HOMEBREW_NO_AUTO_UPDATE=1
      - brew install libimobiledevice
      - brew install ideviceinstaller
      - brew install ios-deploy
      - brew install cocoapods || echo 'ignore exit(1)'
      - brew link --overwrite cocoapods

      # install pre-compiled flutter
#      - FLUTTER_CHANNEL=stable
#      - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL}
#      - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
      # build experimental flutter from fork
      - git clone https://github.com/mmcc007/flutter.git -b master
      - export PATH="$PATH":"$HOME/.pub-cache/bin"
      - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
      - flutter doctor -v

      # install aws
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - unzip awscli-bundle.zip
      - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - aws --version
      - cp -r .aws ~

      # install most current (released or unreleased) version of Sylph
      - pub global activate --source path .

      script:
      - cd example; sylph
      # bundle artifacts for publishing
      - tar cvzf /tmp/sylph-artifacts.tar.gz -C /tmp sylph/artifacts

      # publish artifacts to GitHub
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: OCyFLrBnorKGT3g7uf0BClF85lb+d6KDcvAvZvEiAec4P1GoaYoxz7iXAYEQ7rLBp1QYu94sW6diM2vd4g9V3NAGQAMzFLdVYkIyueHXE+PW4Z4i5SFm8d8VSTck1SCN4gBtd1j3pKbFCMH8637lrZ24uz46f4Gk4qlQ1PVbfkSIFm/eKTtFzRQO4XCOiMj+sHd/M72+jhfzDhwXAi7cG6Qf+cPpvAGLK7mZvsjg6UBrYltn7sOhG6P8XO927GXz/N8VutHvz6Ip0c0yNXpjoMiNub2YMzAxNmnxurabxDhZubtEqwn5bwohOce6mxqC3z6MH5Xq8RUW7BpmpFakHw+usFp1tTQ3QSBeVblZTX++wOzEnvF9vGh0IhMDr8iJBYFGjQtpJyW2Iz0EaU5W64Qh/FxCjgpyqN2hOQY43wLxnK3vpoBiqKOV+ZscXEgyJF0pfnMbFjahU/b/mbGbu6EmQvkWFxN5xnPH0qQ0u2yIlvDydgzWmX3nEjuYTBVFn3eEfQAfjZOEP9bmo3cK4ObyQSaqQAVJPS+ZCkGRlF7WPzJtWQX6kl9wNSAG94dq6MQ8dl/7NrIr1JXNxwcTb/q8CuYEpq6ZrbMlaFCFvgdFdpKqZCoCkD284wnyUUQUDLM3O6Tr2nYNTLHVGriPhcRSjdCVvZYDWo4wx1WYbAY=
        file: /tmp/sylph-artifacts.tar.gz
        on:
          tags: true
