opt_out_usage # disable sending analytics

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
setup_travis # unlock travis keychain (may remove at some point)

# suppress output
def suppress_output
  original_stdout, original_stderr = $stdout.clone, $stderr.clone
  $stderr.reopen File.new('/dev/null', 'w')
  $stdout.reopen File.new('/dev/null', 'w')
  yield
ensure
  $stdout.reopen original_stdout
  $stderr.reopen original_stderr
end

platform :ios do

  desc "enable match code signing"
  lane :enable_match_code_signing do
    puts 'Retrieving signing certificates and profiles...'
    # Stop fastlane from echoing back PUBLISHING_MATCH_CERTIFICATE_REPO var.
    # suppress_output {
      # Retrieves all the necessary certs and provisioning profiles.
      #  force_for_new_devices: true,
      #  readonly: false,
      sync_code_signing(
        git_url: ENV['PUBLISHING_MATCH_CERTIFICATE_REPO'],
        type: 'development',
        keychain_name: 'fastlane_tmp_keychain',
        readonly: true
      )
    # }
    puts 'Certificates and profiles installed'

  app_identifier=CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  puts "app_identifier: #{app_identifier}"
  #profile_name='sigh_' + app_identifier + '_appstore_profile-path'
  profile_name='sigh_' + app_identifier + '_development_profile-path'

#      build_configuration: 'Release',
    update_project_provisioning(
      xcodeproj: 'Runner.xcodeproj',
      target_filter: 'Runner',
      build_configuration: 'Debug',
      profile: ENV[profile_name],
    )
  end


  desc "build debug .app"
  lane :build_debug do
    #pre_build_debug
    enable_match_code_signing
    #disable_automatic_code_signing
    sh ("cd ../.. && flutter build ios --debug")
    #build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    #enable_automatic_code_signing
  end


  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    #upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
